// Static data tables for the Mod Menu: pet stats and the full item catalogue.
#pragma once

#include "base.h"
#include "game_addrs.h"

// Health doubles as the sickness-type field: 0-9 are specific illnesses,
// 10 = Healthy (no sickness), 11 = a generic "Sick" catch-all. Matches the
// in-game Personality screen showing "OK" for Health as a word, not a
// magnitude, the same way Hunger/Mood show words like "Stuffed"/"Ecstatic".
static const char* SICKNESS_NAMES[] = {
    "Dog Breath", "Gone Bananas", "Panda Pox", "Cold", "Molting",
    "Brain Freeze", "Cold Feet", "Brain Ache", "The Oogies", "Cooties",
    "Healthy", "Sick",
};

static const int SICKNESS_NAME_COUNT = sizeof(SICKNESS_NAMES) / sizeof(SICKNESS_NAMES[0]);
static const int SICKNESS_HEALTHY_VALUE = 10;

// A row can optionally carry a preset list (Cheat Engine's DropDownList
// entries, e.g. Quests Completed's named unlock thresholds) - these are
// quick-set shortcuts to known meaningful values, shown via a small "..."
// button that opens a floating picker; the row's normal arrows/wheel/type
// editing still work for any raw value, matching both requirements.
struct CheatPreset { int32_t value; const char* label; };

static const CheatPreset QUESTS_COMPLETED_PRESETS[] = {
    { 3,  "Unlock Downtown" },
    { 13, "Unlock the Beach" },
    { 15, "Unlock Giga Castle" },
    { 16, "Unlock Vacation Island" },
    { 41, "Unlock Gigalympia (Left Entrance)" },
    { 60, "Unlock the Jungle Bridge" },
    { 89, "Unlock Magma Mountain" },
    { 90, "Unlock Gigalympia (Right Entrance)" },
};

static const CheatPreset SICKNESS_PRESETS[] = {
    { 0,  "Dog Breath" },
    { 1,  "Gone Bananas" },
    { 2,  "Panda Pox" },
    { 3,  "Cold" },
    { 4,  "Molting" },
    { 5,  "Brain Freeze" },
    { 6,  "Cold Feet" },
    { 7,  "Brain Ache" },
    { 8,  "The Oogies" },
    { 9,  "Cooties" },
    { 10, "Healthy" },
    { 11, "Sick" },
};

// min_val/max_val per the actual in-game caps: Hunger/Mood/Sleepiness/
// Hygeine are 0-100, Health is 0-10, everything else is treated as
// effectively uncapped (0-65535, the full range a stored uint16_t can hold).
// presets/preset_count default to nullptr/0 when omitted from an
// initializer (aggregate init zero-fills trailing members).
struct CheatStatRow {
    const char* name; uint16_t addr; int32_t min_val; int32_t max_val;
    const CheatPreset* presets; int preset_count;
};

static const CheatStatRow CHEAT_STATS[] = {
    { "Money",       0x0C4D, 0, 65535 },
    { "Halos",       0x2182, 0, 65535 },
    { "Pitchforks",  0x2183, 0, 65535 },
    { "Stars",       0x2184, 0, 65535 },
    { "Lightbulbs",  0x2185, 0, 65535 },
    { "Hunger",      0x2186, 0, 100 },
    { "Health",      0x2187, 0, 100 },
    { "Sickness",    0x218D, 0, 11, SICKNESS_PRESETS, sizeof(SICKNESS_PRESETS) / sizeof(SICKNESS_PRESETS[0]) },
    { "Mood",        0x2189, 0, 100 },
    { "Sleepiness",  0x218A, 0, 100 },
    { "Hygeine",     0x218B, 0, 100 },
    { "Tricks",      0x218C, 0, 3 },
    { "Location ID", 0x1AA4, 0, 65535 },
    { "Player X",    0x1CC1, 0, 65535 },
    { "Player Y",    0x1CC2, 0, 65535 },
    { "Camera X",    0x1AB0, 0, 65535 },
    { "Camera Y",    0x1AB1, 0, 65535 },
    { "Player Color",0x1CC6, 0, 65535 },
    { "Quests Done", 0x1E16, 0, 65535, QUESTS_COMPLETED_PRESETS, sizeof(QUESTS_COMPLETED_PRESETS) / sizeof(QUESTS_COMPLETED_PRESETS[0]) },
};

static const int CHEAT_STAT_COUNT = sizeof(CHEAT_STATS) / sizeof(CHEAT_STATS[0]);

struct InventoryCategory {
    const char* name;
    int start;  // index into INVENTORY_ITEMS
    int count;
};

struct InventoryItem {
    const char* name;
    uint16_t addr;
};

static const InventoryItem INVENTORY_ITEMS[] = {
    // Potions
    { "Ash Potion", 0x0C63 },
    { "Black and White Potion", 0x0C64 },
    { "Gold Potion", 0x0C65 },
    { "Grow Potion", 0x0C66 },
    { "Radioactive Potion", 0x0C67 },
    // Food Items (Still need to separate minipet foods)
    { "Alfalfa Mousse", 0x0C68 },
    { "Angel Food Cake", 0x0C86 },
    { "Bacon Balls", 0x0C69 },
    { "Bamboo Licorice", 0x0C6A },
    { "Banana Split", 0x0C6B },
    { "Biscuit", 0x0C7D },
    { "Buffalo Jerky", 0x0C6C },
    { "Cabbage Bar", 0x0C8E },
    { "Chewy Chow", 0x0C6D },
    { "Coconut Quiche", 0x0C6E },
    { "Cotton Candy", 0x0C8F },
    { "Devil's Food Cake", 0x0C87 },
    { "Dim Some", 0x0C88 },
    { "Einsteinios", 0x0C8B },
    { "Escargot", 0x0C90 },
    { "Fiber Sticks", 0x0C91 },
    { "Fried Bananas", 0x0C6F },
    { "Fried Chocolate", 0x0C7F },
    { "Granola Sprouts", 0x0C7E },
    { "Green Salad", 0x0C84 },
    { "Hagfish Hummus", 0x0C93 },
    { "Lettuce Nuggets", 0x0C70 },
    { "Main Dish", 0x0C81 },
    { "Mango Pops", 0x0C71 },
    { "Meat Loaf", 0x0C7C },
    { "Monkey Meal", 0x0C72 },
    { "Muffin Sprouts", 0x0C73 },
    { "Mulch Meal", 0x0C94 },
    { "Nice Drops", 0x0C8C },
    { "Panda Chips", 0x0C74 },
    { "Parsley Pate", 0x0C95 },
    { "Passion Fruit Salad", 0x0C75 },
    { "Pixie Twigs", 0x0C96 },
    { "Pretty Pies", 0x0C8A },
    { "Roasted Scarab", 0x0C97 },
    { "Romaine Brulee", 0x0C98 },
    { "Shiny Gold", 0x0C92 },
    { "Sour Grapes", 0x0C89 },
    { "Soy Chop", 0x0C76 },
    { "Spinach Smoothie", 0x0C77 },
    { "Steak Puree", 0x0C82 },
    { "Steak Tar Tar", 0x0C78 },
    { "Sugar Ball", 0x0C80 },
    { "Sunshine Bisque", 0x0C99 },
    { "Sushi a la Mode", 0x0C9A },
    { "Table Scraps", 0x0C79 },
    { "Taco Fries", 0x0C7A },
    { "Taco Fries Giga Meal", 0x0C7B },
    { "Tofu", 0x0C83 },
    { "Tuna Smoothie", 0x0C9B },
    { "Vitamins", 0x0C85 },
    { "Wicked Wafers", 0x0C8D },
    // Medicine (still need to separate minipet medicine)
    { "Aspirin", 0x0C9D },
    { "Chicken Soup", 0x0C9F },
    { "Chili Pill", 0x0CA0 },
    { "Cooty B Gone Spray", 0x0CA1 },
    { "EucalyptX", 0x0CA2 },
    { "Four Leaf Clover", 0x0CA4 },
    { "Fur Oil", 0x0CA3 },
    { "Hair Aid", 0x0CAC },
    { "Happy Juice", 0x0C9E },
    { "Heat Pack", 0x0CA5 },
    { "Ickicide", 0x0CA6 },
    { "Molt Cream", 0x0CAA },
    { "Oogy Tonic", 0x0CA7 },
    { "Puppermints", 0x0CA8 },
    { "Sane Salve", 0x0CA9 },
    { "Sea Bath", 0x0C9C },
    { "Sun Cream", 0x0CAB },
    { "Tummy OK", 0x0CAD },
    // House Decorations
    { "Ball of Yarn", 0x0CC8 },
    { "Bamboo Wall", 0x0CED },
    { "Baseball", 0x0CC9 },
    { "Basic Bed", 0x0CC0 },
    { "Basic Food Dish", 0x0CBC },
    { "Basic Window", 0x0CC4 },
    { "Basketball", 0x0CCA },
    { "Beach Ball", 0x0CCB },
    { "Blue Brick Wall", 0x0CE9 },
    { "Bonsai Plant", 0x0CD3 },
    { "Brick Wall", 0x0CE7 },
    { "Checker Floor", 0x0CF1 },
    { "Chew Toy", 0x0CCC },
    { "Chimes", 0x0CE0 },
    { "Crabbage Toy", 0x0CDB },
    { "Diner Bed", 0x0CC1 },
    { "Disco Ball", 0x0CDF },
    { "Dodge Ball", 0x0CCD },
    { "Dog Doll", 0x0CB1 },
    { "Dream Catcher", 0x0CE1 },
    { "Fancy Bed", 0x0CC2 },
    { "Fancy Food Dish", 0x0CBD },
    { "Fuzzy Ball", 0x0CCE },
    { "Giraffe Doll", 0x0CB2 },
    { "Grass Floor", 0x0CF3 },
    { "Green Bamboo Wall", 0x0CEE },
    { "Green Brick Wall", 0x0CE8 },
    { "Green Floor", 0x0CEF },
    { "Hackey Sack", 0x0CCF },
    { "Hamster Doll", 0x0CB3 },
    { "Hanging Lantern", 0x0CE2 },
    { "Hanging Plant", 0x0CE3 },
    { "Kitten Doll", 0x0CB4 },
    { "Lamp", 0x0CD5 },
    { "Lizard Doll", 0x0CB5 },
    { "Magic Orb", 0x0CD0 },
    { "Maori Head", 0x0CD6 },
    { "Metal Food Dish", 0x0CBE },
    { "Monkey Doll", 0x0CB6 },
    { "Ornate Wood Carving", 0x0D07 },
    { "Panda Doll", 0x0CB7 },
    { "Pixie Doll", 0x0CB8 },
    { "Potted Plant", 0x0CDC },
    { "Puffball Doll", 0x0CB9 },
    { "Purple Brick Wall", 0x0CEA },
    { "Purple Checker Floor", 0x0CF2 },
    { "Purple Vase", 0x0CD4 },
    { "Rabbit Doll", 0x0CBA },
    { "Red Brick Wall", 0x0CEC },
    { "Scorpion Doll", 0x0CBB },
    { "Snow Globe", 0x0CD7 },
    { "Special Stuffed Dog", 0x0CAE },
    { "Special Stuffed Monkey", 0x0CAF },
    { "Special Stuffed Panda", 0x0CB0 },
    { "Stress Ball", 0x0CD1 },
    { "Taco Fries Figurine", 0x0CD8 },
    { "Tennis Ball", 0x0CD2 },
    { "Tiki Bed", 0x0CC3 },
    { "Tiki Man Figurine", 0x0CD9 },
    { "Tiki Window", 0x0CC7 },
    { "Top", 0x0CDD },
    { "Trophy", 0x0CDE },
    { "Vase", 0x0CDA },
    { "Wall With Green Trim", 0x0CE5 },
    { "Wall With Purple Trim", 0x0CE6 },
    { "White Walls", 0x0CE4 },
    { "Window With Blinds", 0x0CC5 },
    { "Window With Curtains", 0x0CC6 },
    { "Wood Food Dish", 0x0CBF },
    { "Wooden Floor", 0x0CF0 },
    { "Yellow Brick Wall", 0x0CEB },
    // King's Lost Items
    { "King's Crown", 0x0CFB },
    { "King's Diamond Collar", 0x0CFC },
    { "King's Golden Shield", 0x0D02 },
    { "King's Jeweled Box", 0x0CFD },
    { "King's Magnificent Statue", 0x0CFF },
    { "King's Medallion", 0x0CFE },
    { "King's Royal Cloak", 0x0D04 },
    { "King's Royal Crest", 0x0D03 },
    { "King's Royal Water Dish", 0x0D06 },
    { "King's Scepter", 0x0D01 },
    { "King's Signet Ring", 0x0D05 },
    { "King's Sword", 0x0D00 },
    // Treasure Maps
    { "Taco Fries Place Map", 0x0D0D },
    { "King's Crown Treasure Map", 0x0D0E },
    { "Treasure Map 1", 0x0D0F },
    { "Treasure Map 2", 0x0D10 },
    { "Treasure Map 3", 0x0D11 },
    { "Treasure Map 4", 0x0D12 },
    { "Treasure Map 5", 0x0D13 },
    { "Treasure Map 6", 0x0D14 },
    { "Treasure Map 7", 0x0D15 },
    { "Treasure Map 8", 0x0D16 },
    { "Treasure Map 9", 0x0D17 },
    { "Treasure Map 10", 0x0D18 },
    // Rare Flowers
    { "Alien Flower", 0x0D3B },
    { "Blue Violet", 0x0D30 },
    { "Buttercup", 0x0D31 },
    { "Cow Belle", 0x0D32 },
    { "Daffodil", 0x0D33 },
    { "Dandelion", 0x0D34 },
    { "Magnolia", 0x0D35 },
    { "Pansy", 0x0D36 },
    { "Petunia", 0x0D37 },
    { "Regal Rose", 0x0D38 },
    { "Snow Orchid", 0x0D39 },
    { "White Lily", 0x0D3A },
    // Fishing Items
    { "Angel Fish", 0x0D3F },
    { "Blow Fish", 0x0D40 },
    { "Cat Fish", 0x0D41 },
    { "Gold Fish", 0x0D42 },
    { "Jelly Fish", 0x0D43 },
    { "Old Boot", 0x0D44 },
    { "Old Tire", 0x0D46 },
    { "Seaweed", 0x0D45 },
    { "Stick Fish", 0x0D3E },
    { "Wet Stone", 0x0D56 },
    // Miscellaneous
    { "Bag O' Bad", 0x0C58 },
    { "Bag o' Bucks", 0x0D5A },
    { "Big Bag O' Bad", 0x0C59 },
    { "Big Sack O' Stars", 0x0C5D },
    { "Garden Book 1", 0x0D58 },
    { "Garden Book 2", 0x0D59 },
    { "Giga Island Map", 0x0C52 },
    { "Goody Bag", 0x0C54 },
    { "Got Away", 0x0C51 },
    { "Great Goody Bag", 0x0C55 },
    { "Halo", 0x0C53 },
    { "Huge Bag O' Halos", 0x0C56 },
    { "Huge Bag of Lightbulbs", 0x0C62 },
    { "Huge Bag of Pitchforks", 0x0C5A },
    { "Huge Sack O' Stars", 0x0C5E },
    { "Large Bag o' Bucks", 0x0D5B },
    { "Lightbulb", 0x0C5F },
    { "Mystery Bag", 0x0D5C },
    { "Pitchfork", 0x0C57 },
    { "Sack O' Smarts", 0x0C60 },
    { "Sack O' Stars", 0x0C5C },
    { "Star", 0x0C5B },
    { "Super Sack O' Smarts", 0x0C61 },
    // Quest Collectibles
    { "Arrow Head", 0x0D22 },
    { "Bamboo Stick", 0x0D23 },
    { "Banana", 0x0D24 },
    { "BBQ Bean", 0x0D47 },
    { "Big Fancy Key", 0x0CF5 },
    { "Blue Flower", 0x0D1A },
    { "Blue Gem", 0x0D1D },
    { "Bone", 0x0D25 },
    { "Bronze Coin", 0x0D28 },
    { "Can", 0x0D54 },
    { "Carrot", 0x0D26 },
    { "Coconut", 0x0D27 },
    { "Corkscrew", 0x0CF6 },
    { "Crabbage", 0x0CF7 },
    { "Crown Wanted Poster", 0x0CF8 },
    { "Dinosaur Bone", 0x0D4D },
    { "Fossil", 0x0D4F },
    { "Friendship Token", 0x0CF4 },
    { "Furrywuzzig", 0x0CF9 },
    { "Giga Berry Plant", 0x0D2B },
    { "Gold Coin", 0x0D50 },
    { "Green Apple", 0x0D20 },
    { "Green Gem", 0x0D1E },
    { "Hive of Fireflies", 0x0D3D },
    { "Jade Stone", 0x0D2C },
    { "Key to the City", 0x0CFA },
    { "Magic Plant", 0x0D49 },
    { "Molten Hot Sauce", 0x0D48 },
    { "Old Bottle", 0x0D53 },
    { "Old Trinket", 0x0D4E },
    { "Old Vase", 0x0D51 },
    { "Orange Flower", 0x0D1B },
    { "Pack Rat Poster", 0x0D09 },
    { "Piece of Trash", 0x0D55 },
    { "Plastic Box", 0x0D52 },
    { "Rag Doll", 0x0D08 },
    { "Red Apple", 0x0D21 },
    { "Red Flower", 0x0D1C },
    { "Red Gem", 0x0D1F },
    { "Rose", 0x0D2D },
    { "Royal Badge", 0x0D0A },
    { "Royal Invitation", 0x0D0B },
    { "Salt Crystals", 0x0D4A },
    { "Silver Coin", 0x0D29 },
    { "Silver Weed Plant", 0x0D2A },
    { "Skeleton Key", 0x0D0C },
    { "Soup Stone", 0x0D4B },
    { "Stick", 0x0D2E },
    { "Sunflower", 0x0D2F },
    { "Sweet Pinewood", 0x0D3C },
    { "Taco Fries Secret Recipe", 0x0D19 },
    { "Tangy Root", 0x0D4C },
    { "Treasure Chest", 0x0D57 },
};

static const int INVENTORY_ITEM_COUNT = sizeof(INVENTORY_ITEMS) / sizeof(INVENTORY_ITEMS[0]);

static const InventoryCategory INVENTORY_CATEGORIES[] = {
    { "Potions", 0, 5 },
    { "Food Items (Still need to separate minipet foods)", 5, 52 },
    { "Medicine (still need to separate minipet medicine)", 57, 18 },
    { "House Decorations", 75, 71 },
    { "King's Lost Items", 146, 12 },
    { "Treasure Maps", 158, 12 },
    { "Rare Flowers", 170, 12 },
    { "Fishing Items", 182, 10 },
    { "Miscellaneous", 192, 23 },
    { "Quest Collectibles", 215, 53 },
};

static const int INVENTORY_CATEGORY_COUNT = sizeof(INVENTORY_CATEGORIES) / sizeof(INVENTORY_CATEGORIES[0]);
